try out a different way to view test results

diff --git a/.github/workflows/build_and_test_fuji.yml b/.github/workflows/build_and_test_fuji.yml
--- a/.github/workflows/build_and_test_fuji.yml
+++ b/.github/workflows/build_and_test_fuji.yml
@@ -13,7 +13,7 @@ env:
   PROJECT_PATH: './Fuji_Example'
   PROJECT_NAME: 'Fuji_Tests'
   JS_PROJECT_NAME: 'Fuji_JSTests'
-  TEST_FILENAME: 'NUnitTestResults.md'
+  TEST_FILENAME: 'NUnitTestResults.trx'
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -50,13 +50,23 @@ jobs:
       # Test the selected project
       - name: Run unit tests on the main project
         working-directory: ${{ env.PROJECT_PATH }}
-        run: dotnet test --no-restore --no-build ${{ env.PROJECT_NAME }} --logger:"liquid.md;LogFileName=${{github.workspace}}/${{env.TEST_FILENAME}};"
+        run: dotnet test --no-restore --no-build ${{ env.PROJECT_NAME }} --logger:"trx;LogFileName=${{github.workspace}}/${{env.TEST_FILENAME}};"
       
-      # upload test report as build artifact
-      - name: Upload test report as build artifact
-        uses: actions/upload-artifact@v3
-        # Use always() to always run this step to publish test results even when there are test failures
-        if: ${{always()}}
+      # upload test report as build artifact (unfortunately it doesn't display it nicely)
+    #  - name: Upload test report as build artifact
+    #    uses: actions/upload-artifact@v3
+    #    # Use always() to always run this step to publish test results even when there are test failures
+    #    if: ${{always()}}
+    #    with:
+    #      name: 'NUnit test run'
+    #      path: ${{github.workspace}}/${{env.TEST_FILENAME}}
+      
+      # try out a community developed version that makes it easier to view test results on GitHub
+      # https://github.com/marketplace/actions/test-reporter
+      - name: View Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
         with:
-          name: 'NUnit test run'
-          path: ${{github.workspace}}/${{env.TEST_FILENAME}}
+          name: See NUnit Tests       # Name of the check run which will be created
+          path: ${{github.workspace}}/${{env.TEST_FILENAME}}    # Path to test results
+          reporter: dotnet-trx        # Format of test results
